# *Required* The access token for the org that you wish to send metrics to.
signalFxAccessToken: {"#from": "env:SFX_TOKEN"}

signalFxRealm: {"#from": "env:SFX_REALM", optional: true}
ingestUrl: {"#from": "env:SFX_AGENT_INGEST_URL", optional: true}
apiUrl: {"#from": "env:SFX_AGENT_API_URL", optional: true}

intervalSeconds: 10

logging:
  # Valid values are 'debug', 'info', 'warning', and 'error'
  level: info

collectd:
  configDir: tmp/collectd

monitors:
  - type: heroku-metadata
